networks:
  ethicallynetwork:
    driver: bridge

services:
  web:
    build: . 
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    networks:
      - ethicallynetwork
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      sh -c "a2enmod rewrite && \
             sed -i 's|/var/www/html|/var/www/html|g' /etc/apache2/sites-available/000-default.conf && \
             apachectl -D FOREGROUND"
  
  sql:
    image: mysql:9.3
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - ethicallynetwork
    ports:
      - "3306:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ehc_bfa
